services:
  master:
    image: mysql:8.0
    container_name: db-source
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
    ports:
      - "3306:3306"
    networks:
      - db-network

  replica:
    image: mysql:8.0
    container_name: db-replica
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./custom-replica.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3307:3306"
    depends_on:
      - master
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
